name = "toolset-web"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".vercel/output/static"

[env.production]
compatibility_date = "2024-01-01"

[env.preview]
compatibility_date = "2024-01-01"

